### ISSUE TITLE
Enhancement Request: Show xCloud Games as Uninstalled

### ISSUE THREAD

**Issue by kholdstare622** [joyrider3774/Playnite_XCloud_Library#1]
I would love an option in the settings for this plugin to be able to mark all xCloud games as not installed. I like to group my library by Installed/NotInstalled so I can have my installed games at the top. Having the option to mark all xCloud games as Not Installed will give me the ability to still have them included in my library, but ensure they are excluded from the 10-15 games I typically have installed.

**Comment by mike1237** [comment]
I agree, for example the GEFORCE Now plugin does this so I can filter locally installed games from cloud games.
I don't consider a cloud streaming game "installed". (AKA rendered by my GPU)
EDIT: Although I suppose filtering/grouping by Platform does solve this problem. Would be a nice enhancement to have options though :)

**Comment by joyrider3774** [comment]
I implemented the option but be aware you can not "play" games if they are marked as uninstalled. You can however "install" the games by pressing the install button so you can play that game and also uninstall it again if you don't play the game anymore. Only thing it does is change the installed flag / checkbox but it affects the availability of the play action. I'm not changing that but at least you can now change the setting in the libraries (addon) settings to always put the game as uinstalled and only put it as installed when you want to actually play the game.

Gefore now plugin works differently compared to this library plugin, so games need to be flagged as installed before the "play" action would appear nothing i can do about that

**Comment by mike1237** [comment]
Thank you!
